version: '3.0'
services:
  ruby:
    image: ruby:2.6.3-slim-stretch
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/var/opt/app
